package io.vanillabp.pea.quarkus.runtime;

import java.util.List;
import java.util.Map;

import dev.bpmcrafters.processengineapi.correlation.CorrelationApi;
import dev.bpmcrafters.processengineapi.correlation.SignalApi;
import dev.bpmcrafters.processengineapi.process.StartProcessApi;
import dev.bpmcrafters.processengineapi.task.ServiceTaskCompletionApi;
import dev.bpmcrafters.processengineapi.task.UserTaskCompletionApi;
import io.vanillabp.integration.adapter.migration.config.MigrationAdapterProperties;
import io.vanillabp.integration.adapter.migration.workflowtask.WorkflowTaskRegistry;
import io.vanillabp.integration.adapter.spi.AdapterCollaborators;
import io.vanillabp.integration.adapter.spi.MigratableProcessService;
import io.vanillabp.integration.adapter.spi.NameClashAvoidanceSupport;
import io.vanillabp.integration.adapter.spi.PreCommitRegistrar;
import io.vanillabp.integration.adapter.spi.WorkflowAggregateSync;
import io.vanillabp.integration.adapter.spi.workflowend.WorkflowEndedInvoker;
import io.vanillabp.integration.adapter.spi.workflowstart.BpmsInitiatedStartInvoker;
import io.vanillabp.integration.runtime.support.AdapterCollaboratorsSupport;
import io.vanillabp.pea.PeaAdapter;
import io.vanillabp.pea.deployment.PeaDeployedProcessesRegistry;
import io.vanillabp.pea.processservice.PeaProcessService;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Any;
import jakarta.enterprise.inject.Instance;
import jakarta.enterprise.inject.Produces;

/**
 * Provides the Process-Engine-API adapter's {@link PeaProcessService} as a CDI bean picked
 * up by the process service beans generated by the VanillaBP Quarkus integration. The
 * adapter id is resolved from the configuration (first adapter of type
 * {@code process-engine-api}).
 * <p>
 * The Process-Engine-API interfaces are injected; by default they resolve to the
 * mock-backed {@link io.vanillabp.pea.mock.InMemoryProcessEngine} default bean.
 */
@ApplicationScoped
public class PeaProcessServiceProducer {

  /**
   * Only the Process-Engine-APIs the adapter actually uses are injected (currently
   * {@link StartProcessApi}); upcoming stories add theirs when they consume them.
   */
  /**
   * What the platform hands the adapter, built the same way for both services of an
   * adapter id.
   */
  static AdapterCollaborators collaboratorsOf(
      final String adapterId,
      final WorkflowTaskRegistry workflowTaskRegistry,
      final NameClashAvoidanceSupport scoping,
      final WorkflowAggregateSync aggregateSync,
      final PreCommitRegistrar preCommitRegistrar,
      final Instance<WorkflowEndedInvoker> workflowEndedInvoker,
      final Instance<BpmsInitiatedStartInvoker> bpmsInitiatedStartInvoker) {

    return AdapterCollaboratorsSupport
        .collaborators(
            adapterId, workflowTaskRegistry, workflowTaskRegistry, scoping, aggregateSync, preCommitRegistrar,
            workflowEndedInvoker, bpmsInitiatedStartInvoker);

  }

  @Produces
  public List<MigratableProcessService<Object>> peaMigratableProcessServices(
      final MigrationAdapterProperties properties,
      final StartProcessApi startProcessApi,
      final ServiceTaskCompletionApi serviceTaskCompletionApi,
      final UserTaskCompletionApi userTaskCompletionApi,
      final CorrelationApi correlationApi,
      @Any final Instance<SignalApi> signalApi,
      final PeaDeployedProcessesRegistry deployedProcessesRegistry,
      final WorkflowAggregateSync aggregateSync,
      final NameClashAvoidanceSupport scoping,
      final PreCommitRegistrar preCommitRegistrar,
      final WorkflowTaskRegistry workflowTaskRegistry,
      @Any final Instance<WorkflowEndedInvoker> workflowEndedInvoker,
      @Any final Instance<BpmsInitiatedStartInvoker> bpmsInitiatedStartInvoker) {

    // ONE bean of type List with one instance PER configured adapter id of this
    // adapter's type (a CDI producer cannot yield N element beans for N
    // runtime-configured ids); the platform's collection point flattens List beans
    // alongside element beans. The id set always comes from the platform's core
    // properties.
    return properties
        .adapterTypes()
        .entrySet()
        .stream()
        .filter(adapter -> PeaAdapter.ADAPTER_TYPE.equals(adapter.getValue()))
        .map(Map.Entry::getKey)
        .sorted()
        .<MigratableProcessService<Object>>map(
            adapterId -> {
              final var processService = new PeaProcessService<>(
                  adapterId, startProcessApi, serviceTaskCompletionApi, userTaskCompletionApi, correlationApi, deployedProcessesRegistry
                      .forAdapter(adapterId), collaboratorsOf(
                          adapterId, workflowTaskRegistry, scoping, aggregateSync, preCommitRegistrar,
                          workflowEndedInvoker, bpmsInitiatedStartInvoker));
              // optional: an engine implementation without a SignalApi leaves
              // signals unsupported, which the process service says when asked
              processService
                  .setSignalApi(
                      signalApi.isResolvable()
                          ? signalApi.get()
                          : null);
              return processService;
            })
        .toList();

  }

}
