package io.vanillabp.pea.quarkus.runtime;

import java.util.List;
import java.util.Map;

import dev.bpmcrafters.processengineapi.process.StartProcessApi;
import io.vanillabp.integration.adapter.migration.config.MigrationAdapterProperties;
import io.vanillabp.integration.adapter.spi.MigratableProcessService;
import io.vanillabp.pea.PeaAdapter;
import io.vanillabp.pea.processservice.PeaProcessService;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;

/**
 * Provides the Process-Engine-API adapter's {@link PeaProcessService} as a CDI bean picked
 * up by the process service beans generated by the VanillaBP Quarkus integration. The
 * adapter id is resolved from the configuration (first adapter of type
 * {@code process-engine-api}).
 * <p>
 * The Process-Engine-API interfaces are injected; by default they resolve to the
 * mock-backed {@link io.vanillabp.pea.mock.InMemoryProcessEngine} default bean.
 */
@ApplicationScoped
public class PeaProcessServiceProducer {

  /**
   * Only the Process-Engine-APIs the adapter actually uses are injected (currently
   * {@link StartProcessApi}); upcoming stories add theirs when they consume them.
   */
  @Produces
  public List<MigratableProcessService<Object>> peaMigratableProcessServices(
      final MigrationAdapterProperties properties,
      final StartProcessApi startProcessApi,
      final dev.bpmcrafters.processengineapi.task.ServiceTaskCompletionApi serviceTaskCompletionApi,
      final dev.bpmcrafters.processengineapi.task.UserTaskCompletionApi userTaskCompletionApi) {

    // ONE bean of type List with one instance PER configured adapter id of this
    // adapter's type (a CDI producer cannot yield N element beans for N
    // runtime-configured ids); the platform's collection point flattens List beans
    // alongside element beans. The id set always comes from the platform's core
    // properties.
    return properties
        .adapterTypes()
        .entrySet()
        .stream()
        .filter(adapter -> PeaAdapter.ADAPTER_TYPE.equals(adapter.getValue()))
        .map(Map.Entry::getKey)
        .sorted()
        .<MigratableProcessService<Object>>map(
            adapterId -> new PeaProcessService<>(adapterId, startProcessApi, serviceTaskCompletionApi, userTaskCompletionApi))
        .toList();

  }

}
