<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.vanillabp</groupId>
    <artifactId>process-engine-api-adapter-parent</artifactId>
    <version>2.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>process-engine-api-adapter-test-coverage-report</artifactId>
  <packaging>pom</packaging>
  <name>VanillaBP adapter for the Process-Engine-API - Test coverage report</name>

  <dependencies>
    <dependency>
      <groupId>io.vanillabp</groupId>
      <artifactId>process-engine-api-adapter</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.vanillabp</groupId>
      <artifactId>process-engine-api-mock</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.vanillabp</groupId>
      <artifactId>process-engine-api-adapter-spring-boot</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.vanillabp</groupId>
      <artifactId>process-engine-api-adapter-quarkus</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>io.vanillabp</groupId>
      <artifactId>process-engine-api-adapter-quarkus-deployment</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>${jacoco.version}</version>
        <executions>
          <execution>
            <goals>
              <!-- 'report-aggregate' sums up all '*.exec' files found in the modules listed in <dependencies> into one report -->
              <goal>report-aggregate</goal>
            </goals>
            <phase>verify</phase>
            <configuration>
              <outputDirectory>${project.basedir}/report</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
